<a href="https://colab.research.google.com/github/0ffs3c/python-git/blob/main/Copy_of_50_Startups.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Step - 1** : Read CSV

In [ ]:
import pandas as pd
import numpy as np
data = pd.read_csv("50_Startups_MLR.csv")
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

# **Step - 2** : Separate both i/p & o/p

## Independent Variables - R&D Spend, Administration, Marketing Spend, State

In [ ]:
X = data.iloc[:,0:4].values

## Dependent Variables - Profit

In [ ]:
Y = data.iloc[:, -1].values

# **Step - 3** : Handle Missing Data

In [ ]:
data['Marketing Spend'] = data['Marketing Spend'].replace(0,np.nan)
data['R&D Spend'] = data['R&D Spend'].replace(0,np.nan)
data['Administration'] = data['Administration'].replace(0,np.nan)
data.tail

<bound method NDFrame.tail of     R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  

In [ ]:
from sklearn.impute import SimpleImputer
values=[0,0.00]
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
X[:, 0:3] = imputer.fit_transform(X[:, 0:3])
print(X)

[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.55 407934.54 'Florida']
 [144372.41 118671.85 383199.62 'New York']
 [142107.34 91391.77 366168.42 'Florida']
 [131876.9 99814.71 362861.36 'New York']
 [134615.46 147198.87 127716.82 'California']
 [130298.13 145530.06 323876.68 'Florida']
 [120542.52 148718.95 311613.29 'New York']
 [123334.88 108679.17 304981.62 'California']
 [101913.08 110594.11 229160.95 'Florida']
 [100671.96 91790.61 249744.55 'California']
 [93863.75 127320.38 249839.44 'Florida']
 [91992.39 135495.07 252664.93 'California']
 [119943.24 156547.42 256512.92 'Florida']
 [114523.61 122616.84 261776.23 'New York']
 [78013.11 121597.55 264346.06 'California']
 [94657.16 145077.58 282574.31 'New York']
 [91749.16 114175.79 294919.57 'Florida']
 [86419.7 153514.11 0.0 'New York']
 [76253.86 113867.3 298664.47 'California']
 [78389.47 153773.43 299737.29 'New York']
 [73994.56 122782.75 303319.26 'Florida']
 [67532

# **Step - 4** : Handle Categorical Data

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
composer = ColumnTransformer(transformers= [('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X =composer.fit_transform(X)
print(X)

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [0.0 1.0 0.0 73994.56 122782.75 3

# **Step - 5** : Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X[:, 0:3] = scaler.fit_transform(X[:, 0:3])
print(X)

[[-0.7177405625652736 -0.6859943405700356 1.3932610920384718 165349.2
  136897.8 471784.1]
 [1.3932610920384723 -0.6859943405700356 -0.7177405625652735 162597.7
  151377.59 443898.53]
 [-0.7177405625652736 1.4577379737113254 -0.7177405625652735 153441.51
  101145.55 407934.54]
 [-0.7177405625652736 -0.6859943405700356 1.3932610920384718 144372.41
  118671.85 383199.62]
 [-0.7177405625652736 1.4577379737113254 -0.7177405625652735 142107.34
  91391.77 366168.42]
 [-0.7177405625652736 -0.6859943405700356 1.3932610920384718 131876.9
  99814.71 362861.36]
 [1.3932610920384723 -0.6859943405700356 -0.7177405625652735 134615.46
  147198.87 127716.82]
 [-0.7177405625652736 1.4577379737113254 -0.7177405625652735 130298.13
  145530.06 323876.68]
 [-0.7177405625652736 -0.6859943405700356 1.3932610920384718 120542.52
  148718.95 311613.29]
 [1.3932610920384723 -0.6859943405700356 -0.7177405625652735 123334.88
  108679.17 304981.62]
 [-0.7177405625652736 1.4577379737113254 -0.7177405625652735 101913

# **Step - 6** : Splitting

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2)

In [ ]:
X_train

array([[-0.7177405625652736, 1.4577379737113254, -0.7177405625652735,
        27892.92, 84710.77, 164470.71],
       [-0.7177405625652736, -0.6859943405700356, 1.3932610920384718,
        86419.7, 153514.11, 0.0],
       [-0.7177405625652736, 1.4577379737113254, -0.7177405625652735,
        55493.95, 103057.49, 214634.81],
       [-0.7177405625652736, 1.4577379737113254, -0.7177405625652735,
        75328.87, 144135.98, 134050.07],
       [-0.7177405625652736, 1.4577379737113254, -0.7177405625652735,
        73994.56, 122782.75, 303319.26],
       [-0.7177405625652736, 1.4577379737113254, -0.7177405625652735,
        28663.76, 127056.21, 201126.82],
       [1.3932610920384723, -0.6859943405700356, -0.7177405625652735,
        23640.93, 96189.63, 148001.11],
       [-0.7177405625652736, 1.4577379737113254, -0.7177405625652735,
        93863.75, 127320.38, 249839.44],
       [1.3932610920384723, -0.6859943405700356, -0.7177405625652735,
        0.0, 116983.8, 45173.06],
       [1.3932610