<a href="https://colab.research.google.com/github/0ffs3c/python-git/blob/main/Data_preprocessing_template_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Step - 1** : Import Data

In [38]:
import pandas as pd
data = pd.read_csv('Salary_Data_SLR.csv')
data.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

# **Step - 2** : Separate both i/p & o/p

In [39]:
X = data.iloc[:,0].values
X = X.reshape(-1,1)
print(X)


[[ 1.1]
 [ 1.3]
 [ 1.5]
 [ 2. ]
 [ 2.2]
 [ 2.9]
 [ 3. ]
 [ 3.2]
 [ 3.2]
 [ 3.7]
 [ 3.9]
 [ 4. ]
 [ 4. ]
 [ 4.1]
 [ 4.5]
 [ 4.9]
 [ 5.1]
 [ 5.3]
 [ 5.9]
 [ 6. ]
 [ 6.8]
 [ 7.1]
 [ 7.9]
 [ 8.2]
 [ 8.7]
 [ 9. ]
 [ 9.5]
 [ 9.6]
 [10.3]
 [10.5]]


In [40]:
Y = data.iloc[:,-1].values
print(Y)

[ 39343.  46205.  37731.  43525.  39891.  56642.  60150.  54445.  64445.
  57189.  63218.  55794.  56957.  57081.  61111.  67938.  66029.  83088.
  81363.  93940.  91738.  98273. 101302. 113812. 109431. 105582. 116969.
 112635. 122391. 121872.]


# **Step - 3** : Splitting the data into train and test.

In [41]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2)
print(X_train)

[[ 6.8]
 [ 1.5]
 [ 2.9]
 [ 4.5]
 [ 9. ]
 [ 9.5]
 [ 1.1]
 [ 7.1]
 [ 6. ]
 [ 3.9]
 [10.5]
 [ 1.3]
 [ 4.9]
 [ 3.2]
 [ 5.3]
 [ 5.1]
 [ 7.9]
 [ 3.7]
 [ 4. ]
 [ 5.9]
 [ 4.1]
 [ 2. ]
 [ 8.7]
 [ 3.2]]


# **Step - 4** : Model

In [42]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression().fit(X_train, Y_train)
print(regressor.intercept_,
regressor.coef_)

26727.51231175376 [9287.11469712]


In [43]:
regressor.predict([[2]])

array([45301.74170599])

In [44]:
regressor.predict(X_test)

array([ 47159.16464541, 122384.79369205, 115883.81340407,  63875.97110022,
       102881.85282811,  54588.8564031 ])

In [45]:
Y_test

array([ 39891., 122391., 112635.,  55794., 113812.,  60150.])